#!/usr/bin/env bash
# Builds the Rust core for the macOS app:
#   1. lt-ffi as a static library for aarch64-apple-darwin
#   2. the UniFFI Swift bindings for it
#
# Called by the "Build Rust core" Run Script phase in apps/macos (see project.yml),
# by CI, and by hand. CONFIGURATION=Release builds the release profile; anything
# else builds debug.
#
# Outputs (build products, never committed):
#   target/aarch64-apple-darwin/{debug,release}/liblt_ffi.a
#   apps/macos/Generated/lt_ffi.swift, lt_ffiFFI.h, module.modulemap
#   apps/macos/Generated/RustBuildInfo.swift  (lt-core's crate version, for tests)
set -euo pipefail

fail() {
    # "error:" makes Xcode show the message as a build error.
    echo "error: build-rust.sh: $*" >&2
    exit 1
}
trap 'fail "\"$BASH_COMMAND\" failed with exit code $? (line $LINENO)"' ERR

# Xcode runs build scripts with a minimal PATH that doesn't include rustup.
export PATH="$HOME/.cargo/bin:$PATH"
command -v cargo >/dev/null 2>&1 ||
    fail "cargo not found. Install Rust from https://rustup.rs (it should live in ~/.cargo/bin)."

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
TARGET="aarch64-apple-darwin"
GEN_DIR="$REPO_ROOT/apps/macos/Generated"

case "${CONFIGURATION:-Debug}" in
    Release) PROFILE="release"; PROFILE_FLAGS=(--release) ;;
    *)       PROFILE="debug";   PROFILE_FLAGS=() ;;
esac
LIB="$REPO_ROOT/target/$TARGET/$PROFILE/liblt_ffi.a"

cd "$REPO_ROOT"

echo "note: building lt-ffi ($PROFILE, $TARGET)"
cargo build --locked -p lt-ffi --target "$TARGET" ${PROFILE_FLAGS[@]+"${PROFILE_FLAGS[@]}"}
[[ -f "$LIB" ]] || fail "cargo succeeded but $LIB is missing"

echo "note: generating Swift bindings"
STAGING="$(mktemp -d)"
trap 'rm -rf "$STAGING"' EXIT
cargo run --locked --quiet -p uniffi-bindgen --bin uniffi-bindgen-swift -- \
    "$LIB" "$STAGING" \
    --swift-sources --headers --modulemap \
    --module-name lt_ffiFFI --modulemap-filename module.modulemap

CORE_VERSION="$(cargo pkgid --locked -p lt-core | sed -E 's/.*[#@]//')"
[[ -n "$CORE_VERSION" ]] || fail "could not read lt-core's version from cargo pkgid"
cat > "$STAGING/RustBuildInfo.swift" <<SWIFT
// Generated by scripts/build-rust.sh. Do not edit.
enum RustBuildInfo {
    /// lt-core's version from its Cargo manifest, read at build time.
    static let ltCoreCrateVersion = "$CORE_VERSION"
}
SWIFT

for f in lt_ffi.swift lt_ffiFFI.h module.modulemap RustBuildInfo.swift; do
    [[ -f "$STAGING/$f" ]] || fail "bindgen did not produce $f"
done

# Copy only files that changed, so Xcode doesn't recompile Swift on every build.
mkdir -p "$GEN_DIR"
for f in "$STAGING"/*; do
    dest="$GEN_DIR/$(basename "$f")"
    cmp -s "$f" "$dest" || cp "$f" "$dest"
done

echo "note: Rust core ready: $LIB"
